In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from matplotlib.colors import LogNorm

sns.set_theme()

# jupyter notebook full-width display
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# no text wrapping
display(HTML("<style>.dataframe td { white-space: nowrap; }</style>"))

# pandas formatting
pd.set_option('display.float_format', '{:.3f}'.format)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

# import files
df_LF = pd.read_pickle('gaspereau_lengthfrequency.pickle')
df_FD = pd.read_pickle('gaspereau_fishdetails.pickle')
df_SD = pd.read_pickle('gaspereau_sample.pickle')

In [4]:
# fish are not ordered correctly
df_FD.sort_values(['sample_id','fish_number']).reset_index(drop=True).head(100)

,sample_id,DATETIME,SITE,PERIOD,CONDITION,fish_number,FL_WET,FL_FROZEN,fish_length,fish_weight,SPECIES,SEX,maturity_id,gonad_weight,AGER_1,AGE_1,FSP_1,COMMENTS_1,AGER_2,AGE_2,FSP_2,COMMENTS_2,AGER_3,AGE_3,FSP_3,COMMENTS_3,ENVELOP_COMMENTS,remarks
0,1983050912,1983-05-09,12,NaN,Fresh,1,285,<NA>,285,336.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
1,1983050912,1983-05-09,12,NaN,Fresh,2,288,<NA>,288,334.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
2,1983050912,1983-05-09,12,NaN,Fresh,3,280,<NA>,280,364.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
3,1983050912,1983-05-09,12,NaN,Fresh,4,286,<NA>,286,353.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
4,1983050912,1983-05-09,12,NaN,Fresh,5,297,<NA>,297,370.000,A,F,2,NaN,NaN,6,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 6; FSP_notes_1: 4
5,1983050912,1983-05-09,12,NaN,Fresh,6,271,<NA>,271,294.000,A,M,2,NaN,NaN,6,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 6; FSP_notes_1: 3
6,1983050912,1983-05-09,12,NaN,Fresh,7,277,<NA>,277,333.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
7,1983050912,1983-05-09,12,NaN,Fresh,8,276,<NA>,276,300.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
8,1983050912,1983-05-09,12,NaN,Fresh,9,285,<NA>,285,366.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
9,1983050912,1983-05-09,12,NaN,Fresh,10,276,<NA>,276,318.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
10,1983050912,1983-05-09,12,NaN,Fresh,11,280,<NA>,280,323.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
11,1983051212,1983-05-12,12,NaN,Fresh,1,288,<NA>,288,363.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
12,1983051212,1983-05-12,12,NaN,Fresh,2,280,<NA>,280,325.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
13,1983051212,1983-05-12,12,NaN,Fresh,3,277,<NA>,277,272.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
14,1983051212,1983-05-12,12,NaN,Fresh,4,279,<NA>,279,310.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
15,1983051212,1983-05-12,12,NaN,Fresh,5,253,<NA>,253,228.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
16,1983051212,1983-05-12,12,NaN,Fresh,6,299,<NA>,299,356.000,A,M,2,NaN,NaN,9,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 9; FSP_notes_1: 3
17,1983051212,1983-05-12,12,NaN,Fresh,7,293,<NA>,293,363.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
18,1983051212,1983-05-12,12,NaN,Fresh,8,279,<NA>,279,282.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
19,1983051212,1983-05-12,12,NaN,Fresh,9,285,<NA>,285,350.000,A,F,2,NaN,NaN,5,5,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 5
20,1983051212,1983-05-12,12,NaN,Fresh,10,251,<NA>,251,227.000,A,F,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
21,1983051212,1983-05-12,12,NaN,Fresh,11,247,<NA>,247,214.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
22,1983051212,1983-05-12,12,NaN,Fresh,12,287,<NA>,287,374.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
23,1983051212,1983-05-12,12,NaN,Fresh,13,264,<NA>,264,243.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
24,1983051212,1983-05-12,12,NaN,Fresh,14,270,<NA>,270,317.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
25,1983051212,1983-05-12,12,NaN,Fresh,15,268,<NA>,268,259.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
26,1983051212,1983-05-12,12,NaN,Fresh,16,255,<NA>,255,231.000,A,F,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
27,1983051212,1983-05-12,12,NaN,Fresh,17,274,<NA>,274,322.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
28,1983051412,1983-05-14,12,NaN,Fresh,1,269,<NA>,269,309.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
29,1983051412,1983-05-14,12,NaN,Fresh,2,309,<NA>,309,363.000,A,F,2,NaN,NaN,7,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 7; FSP_notes_1: 3
30,1983051412,1983-05-14,12,NaN,Fresh,3,287,<NA>,287,343.000,A,M,2,NaN,NaN,7,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 7; FSP_notes_1: 3
31,1983051412,1983-05-14,12,NaN,Fresh,4,275,<NA>,275,316.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
32,1983051412,1983-05-14,12,NaN,Fresh,5,271,<NA>,271,287.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
33,1983051412,1983-05-14,12,NaN,Fresh,6,269,<NA>,269,253.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
34,1983051412,1983-05-14,12,NaN,Fresh,7,247,<NA>,247,213.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
35,1983051412,1983-05-14,12,NaN,Fresh,8,258,<NA>,258,251.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
36,1983051412,1983-05-14,12,NaN,Fresh,9,257,<NA>,257,245.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
37,1983051412,1983-05-14,12,NaN,Fresh,10,282,<NA>,282,341.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
38,1983051412,1983-05-14,12,NaN,Fresh,11,270,<NA>,270,300.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
39,1983051412,1983-05-14,12,NaN,Fresh,12,269,<NA>,269,331.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
40,1983051412,1983-05-14,12,NaN,Fresh,13,259,<NA>,259,245.000,A,F,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
41,1983051412,1983-05-14,12,NaN,Fresh,14,279,<NA>,279,337.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
42,1983051412,1983-05-14,12,NaN,Fresh,15,255,<NA>,255,235.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
43,1983051412,1983-05-14,12,NaN,Fresh,16,268,<NA>,268,269.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
44,1983051412,1983-05-14,12,NaN,Fresh,17,285,<NA>,285,361.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
45,1983051412,1983-05-14,12,NaN,Fresh,18,265,<NA>,265,270.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
46,1983051412,1983-05-14,12,NaN,Fresh,19,275,<NA>,275,305.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
47,1983051412,1983-05-14,12,NaN,Fresh,20,280,<NA>,280,328.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
48,1983051412,1983-05-14,12,NaN,Fresh,21,268,<NA>,268,272.000,A,M,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
49,1983051412,1983-05-14,12,NaN,Fresh,22,271,<NA>,271,286.000,A,M,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
50,1983051412,1983-05-14,12,NaN,Fresh,23,270,<NA>,270,320.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
51,1983051412,1983-05-14,12,NaN,Fresh,24,265,<NA>,265,295.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
52,1983051412,1983-05-14,12,NaN,Fresh,25,275,<NA>,275,301.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
53,1983051412,1983-05-14,12,NaN,Fresh,26,276,<NA>,276,306.000,A,M,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
54,1983051412,1983-05-14,12,NaN,Fresh,27,279,<NA>,279,354.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
55,1983051412,1983-05-14,12,NaN,Fresh,28,275,<NA>,275,323.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
56,1983051412,1983-05-14,12,NaN,Fresh,29,270,<NA>,270,312.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
57,1983051412,1983-05-14,12,NaN,Fresh,30,290,<NA>,290,354.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3
58,1983051412,1983-05-14,12,NaN,Fresh,31,277,<NA>,277,293.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
59,1983051412,1983-05-14,12,NaN,Fresh,32,278,<NA>,278,273.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
60,1983051412,1983-05-14,12,NaN,Fresh,33,270,<NA>,270,277.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
61,1983051412,1983-05-14,12,NaN,Fresh,34,305,<NA>,305,416.000,A,F,2,NaN,NaN,7,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 7; FSP_notes_1: 3
62,1983051412,1983-05-14,12,NaN,Fresh,35,277,<NA>,277,272.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
63,1983051412,1983-05-14,12,NaN,Fresh,36,248,<NA>,248,222.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
64,1983051412,1983-05-14,12,NaN,Fresh,37,252,<NA>,252,227.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
65,1983051412,1983-05-14,12,NaN,Fresh,38,255,<NA>,255,242.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
66,1983051412,1983-05-14,12,NaN,Fresh,39,290,<NA>,290,380.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
67,1983051412,1983-05-14,12,NaN,Fresh,40,275,<NA>,275,308.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
68,1983051412,1983-05-14,12,NaN,Fresh,41,255,<NA>,255,223.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
69,1983051412,1983-05-14,12,NaN,Fresh,42,270,<NA>,270,259.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
70,1983051412,1983-05-14,12,NaN,Fresh,43,275,<NA>,275,303.000,A,M,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
71,1983051412,1983-05-14,12,NaN,Fresh,44,272,<NA>,272,292.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
72,1983051412,1983-05-14,12,NaN,Fresh,45,285,<NA>,285,324.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
73,1983051412,1983-05-14,12,NaN,Fresh,46,270,<NA>,270,285.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
74,1983051412,1983-05-14,12,NaN,Fresh,47,280,<NA>,280,374.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
75,1983051412,1983-05-14,12,NaN,Fresh,48,308,<NA>,308,460.000,A,F,2,NaN,NaN,7,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 7; FSP_notes_1: 3
76,1983051412,1983-05-14,12,NaN,Fresh,49,269,<NA>,269,269.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
77,1983051412,1983-05-14,12,NaN,Fresh,50,265,<NA>,265,280.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
78,1983051412,1983-05-14,12,NaN,Fresh,51,270,<NA>,270,273.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
79,1983051412,1983-05-14,12,NaN,Fresh,52,275,<NA>,275,284.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
80,1983051412,1983-05-14,12,NaN,Fresh,53,290,<NA>,290,330.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
81,1983051412,1983-05-14,12,NaN,Fresh,54,270,<NA>,270,272.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
82,1983051412,1983-05-14,12,NaN,Fresh,55,288,<NA>,288,356.000,A,F,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
83,1983051412,1983-05-14,12,NaN,Fresh,56,290,<NA>,290,349.000,A,F,2,NaN,NaN,6,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 6; FSP_notes_1: 4
84,1983051612,1983-05-16,12,NaN,Frozen,1,<NA>,275,283,329.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
85,1983051612,1983-05-16,12,NaN,Frozen,2,<NA>,250,258,239.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
86,1983051612,1983-05-16,12,NaN,Frozen,3,<NA>,240,248,202.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
87,1983051612,1983-05-16,12,NaN,Frozen,4,<NA>,245,253,245.000,A,M,2,NaN,NaN,3,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 3; FSP_notes_1: 3
88,1983051612,1983-05-16,12,NaN,Frozen,5,<NA>,272,280,297.000,A,M,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
89,1983051612,1983-05-16,12,NaN,Frozen,6,<NA>,260,268,287.000,A,M,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
90,1983051612,1983-05-16,12,NaN,Frozen,7,<NA>,262,270,309.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
91,1983051612,1983-05-16,12,NaN,Frozen,8,<NA>,265,273,264.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
92,1983051612,1983-05-16,12,NaN,Frozen,9,<NA>,265,273,298.000,A,F,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
93,1983051612,1983-05-16,12,NaN,Frozen,10,<NA>,260,268,263.000,A,M,2,NaN,NaN,4,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 4
94,1983051612,1983-05-16,12,NaN,Frozen,11,<NA>,300,309,419.000,A,F,2,NaN,NaN,8,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 8; FSP_notes_1: 4
95,1983051612,1983-05-16,12,NaN,Frozen,12,<NA>,265,273,213.000,A,M,2,NaN,NaN,4,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 4; FSP_notes_1: 3
96,1983051612,1983-05-16,12,NaN,Frozen,13,<NA>,280,289,331.000,A,M,2,NaN,NaN,8,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 8; FSP_notes_1: 3
97,1983051612,1983-05-16,12,NaN,Frozen,14,<NA>,280,289,330.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
98,1983051612,1983-05-16,12,NaN,Frozen,15,<NA>,285,294,350.000,A,F,2,NaN,NaN,5,4,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 4
99,1983051612,1983-05-16,12,NaN,Frozen,16,<NA>,275,283,330.000,A,F,2,NaN,NaN,5,3,NaN,NaN,<NA>,<NA>,NaN,NaN,<NA>,<NA>,NaN,NaN,SITE_notes: 12; AGE_notes_1: 5; FSP_notes_1: 3